<a href="https://colab.research.google.com/github/laurarigau/Food-Sustainability/blob/main/notebooks/03_recipe_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

## Create Initial Recipe Dataset.

In [2]:
recipes_data = [
    {
        "recipe_id": "R001",
        "recipe_name": "Tomato Pasta",
        "servings": 2,
        "dietary_tag": "vegetarian"
    },
    {
        "recipe_id": "R002",
        "recipe_name": "Chicken Rice",
        "servings": 2,
        "dietary_tag": "omnivore"
    },
    {
        "recipe_id": "R003",
        "recipe_name": "Lentil Salad",
        "servings": 2,
        "dietary_tag": "vegan"
    },
    {
        "recipe_id": "R004",
        "recipe_name": "Vegetable Stir Fry",
        "servings": 2,
        "dietary_tag": "vegan"
    },
    {
        "recipe_id": "R005",
        "recipe_name": "Beef Bolognese",
        "servings": 2,
        "dietary_tag": "omnivore"
    }
]

recipes_df = pd.DataFrame(recipes_data)

display(recipes_df)

  recipe_id         recipe_name  servings dietary_tag
0      R001        Tomato Pasta         2  vegetarian
1      R002        Chicken Rice         2    omnivore
2      R003        Lentil Salad         2       vegan
3      R004  Vegetable Stir Fry         2       vegan
4      R005      Beef Bolognese         2    omnivore

## Create Recipe Ingredients Dataset.

In [3]:
ingredients_data = [
    # Tomato Pasta
    ("R001", "pasta", 180),
    ("R001", "tomato", 250),
    ("R001", "olive oil", 20),
    ("R001", "garlic", 10),

    # Chicken Rice
    ("R002", "chicken", 250),
    ("R002", "rice", 160),
    ("R002", "carrot", 100),
    ("R002", "olive oil", 20),

    # Lentil Salad
    ("R003", "lentils", 200),
    ("R003", "tomato", 150),
    ("R003", "onion", 80),
    ("R003", "olive oil", 20),

    # Vegetable Stir Fry
    ("R004", "broccoli", 200),
    ("R004", "carrot", 150),
    ("R004", "bell pepper", 150),
    ("R004", "rice", 160),

    # Beef Bolognese
    ("R005", "beef", 250),
    ("R005", "pasta", 180),
    ("R005", "tomato", 200),
    ("R005", "onion", 80)
]

ingredients_df = pd.DataFrame(
    ingredients_data,
    columns=["recipe_id", "ingredient", "quantity_g"]
)

display(ingredients_df)

   recipe_id   ingredient  quantity_g
0       R001        pasta         180
1       R001       tomato         250
2       R001    olive oil          20
3       R001       garlic          10
4       R002      chicken         250
5       R002         rice         160
6       R002       carrot         100
7       R002    olive oil          20
8       R003      lentils         200
9       R003       tomato         150
10      R003        onion          80
11      R003    olive oil          20
12      R004     broccoli         200
13      R004       carrot         150
14      R004  bell pepper         150
15      R004         rice         160
16      R005         beef         250
17      R005        pasta         180
18      R005       tomato         200
19      R005        onion          80

## Data Validation

In [4]:
print("Total recipes:", len(recipes_df))
print("Total ingredient entries:", len(ingredients_df))

print("\nMissing recipe values:")
print(recipes_df.isnull().sum())

print("\nMissing ingredient values:")
print(ingredients_df.isnull().sum())

print("\nInvalid quantities:",
      (ingredients_df["quantity_g"] <= 0).sum())

print("\nUnknown recipe IDs:",
      (~ingredients_df["recipe_id"].isin(
          recipes_df["recipe_id"]
      )).sum())

print("\nDuplicated recipe IDs:",
      recipes_df["recipe_id"].duplicated().sum())

Total recipes: 5
Total ingredient entries: 20

Missing recipe values:
recipe_id      0
recipe_name    0
servings       0
dietary_tag    0
dtype: int64

Missing ingredient values:
recipe_id     0
ingredient    0
quantity_g    0
dtype: int64

Invalid quantities: 0

Unknown recipe IDs: 0

Duplicated recipe IDs: 0

In [5]:
recipes_df.to_csv("recipes.csv", index=False)

ingredients_df.to_csv(
    "recipe_ingredients.csv",
    index=False
)

print("Datasets saved successfully!")

Datasets saved successfully!

## Ingredient Standardization

In [6]:
# Standardize ingredient names

ingredient_mapping = {
    "tomatoes": "tomato",
    "lentils": "lentil",
    "carrots": "carrot",
    "onions": "onion",
    "potatoes": "potato",
    "bell peppers": "bell pepper"
}

ingredients_df["ingredient_clean"] = (
    ingredients_df["ingredient"]
    .str.lower()
    .str.strip()
    .replace(ingredient_mapping)
)

display(
    ingredients_df[
        ["ingredient", "ingredient_clean"]
    ]
)

     ingredient ingredient_clean
0         pasta            pasta
1        tomato           tomato
2     olive oil        olive oil
3        garlic           garlic
4       chicken          chicken
5          rice             rice
6        carrot           carrot
7     olive oil        olive oil
8       lentils           lentil
9        tomato           tomato
10        onion            onion
11    olive oil        olive oil
12     broccoli         broccoli
13       carrot           carrot
14  bell pepper      bell pepper
15         rice             rice
16         beef             beef
17        pasta            pasta
18       tomato           tomato
19        onion            onion

In [7]:
unique_ingredients = sorted(
    ingredients_df["ingredient_clean"].unique()
)

print("Total unique ingredients:", len(unique_ingredients))

print("\nIngredients:")
for ingredient in unique_ingredients:
    print("-", ingredient)

Total unique ingredients: 12

Ingredients:
- beef
- bell pepper
- broccoli
- carrot
- chicken
- garlic
- lentil
- olive oil
- onion
- pasta
- rice
- tomato

In [8]:
ingredients_df.to_csv(
    "recipe_ingredients.csv",
    index=False
)

print("Updated ingredient dataset saved!")

Updated ingredient dataset saved!

In [ ]:
# Standardize ingredient names

ingredient_mapping = {
    "tomatoes": "tomato",
    "lentils": "lentil",
    "carrots": "carrot",
    "onions": "onion",
    "potatoes": "potato",
    "bell peppers": "bell pepper"
}

ingredients_df["ingredient_clean"] = (
    ingredients_df["ingredient"]
    .str.lower()
    .str.strip()
    .replace(ingredient_mapping)
)

# Check unique ingredients
unique_ingredients = sorted(
    ingredients_df["ingredient_clean"].unique()
)

print("Total unique ingredients:", len(unique_ingredients))

for ingredient in unique_ingredients:
    print("-", ingredient)

In [ ]:
ingredients_df.to_csv(
    "recipe_ingredients.csv",
    index=False
)

print("Standardized ingredients saved!")